### ISSUE TITLE
Support for distinct

### ISSUE THREAD

**Issue by Karluzo** [orlando-colamatteo/ms-sql-server-group-concat-sqlclr#23]
In MySQL there is support for DISTINCT in GROUP_CONCAT. It is not included in this project, though it can be achieved very simply by  commenting the `for` cycle in the `Terminate` method. It would be nice to have it included in the published project. ORDER BY and SEPARATOR are already supported.

**Comment by mgandley** [comment]
Already works.  Just put DISTINCT inside the aggregate, before the data you're aggregating.

dbo.CONCAT(DISTINCT name, ', ')
