### ISSUE TITLE
Weird results using GROUP_CONCAT_D with trailing spaces and underscores

### ISSUE THREAD

**Issue by dataflownow** [orlando-colamatteo/ms-sql-server-group-concat-sqlclr#27]
We are using version 1.0.4877.40948 of GROUP_CONCAT.  Apologies is this issue has been fixed in a later version. (How to check version?)

dbo.GROUP_CONCAT_D(\<field\>,N', ') [comma with trailing space] works as expected but dbo.GROUP_CONCAT_D(\<field\>,N' and ') results in the trailing space in the delimiter being lost.  Underscore characters in the delimiter return stranger results: dbo.GROUP_CONCAT_D(\<field\>,N'\_\_and\_\_') results in \<field\>\_\_an\<field\>\_\_an\<field\>...

**Comment by orlando-colamatteo** [comment]
The function accepts a max of 4 characters as a delimiter hence why you are losing the trailing space when passing ' and ' and the trailing 'd__' when passing '__and__'. Wider delimiters can affect performance and 4 was deemed a compromise to allow for plenty of unique options while still keeping it relatively narrow. If you need to support wider delimiters you can expand the SqlFacet in the C# code and redeploy the function.
